apiVersion: v1
kind: Service
metadata:
  name: api-gateway-clima
spec:
  type: ClusterIP
  selector:
    app: api-gateway-clima-app
  ports:
    - port: 4000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-clima
spec:
  selector:
    matchLabels:
      app: api-gateway-clima-app
  template:
    metadata:
      labels:
        app: api-gateway-clima-app
    spec:
      containers:
        - name: api-gateway-clima-container
          image: ghcr.io/joaquinuc150/api-gateway-granjabot:main
          imagePullPolicy: Always
          ports:
            - containerPort: 4000